# \u901A\u7528\u670D\u52A1\u914D\u7F6E
server:
  port: 8090
  servlet:
    context-path: /Recognize
spring:
  # \u8BBE\u7F6E\u9ED8\u8BA4\u914D\u7F6E\u6D3B\u8DC3\u6587\u4EF6
  profiles:
    active: dev
  jackson:
    # jackson\u65F6\u95F4\u683C\u5F0F\u5316
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#    default-property-inclusion: non_empty
